#!/usr/bin/env bash
# Copyright © 2026 Georges Bou Ghantous. All Rights Reserved.
# SHIELD Scanner - Container Entrypoint Wrapper
# 
# This script runs the SHIELD Framework and consolidates outputs.

set -euo pipefail

FRAMEWORK_DIR="/app/framework"
OUTPUT_DIR="/app/output"

# Show help if no args or --help
if [[ $# -eq 0 || "$1" == "--help" || "$1" == "-h" ]]; then
    echo "SHIELD Scanner Container"
    echo ""
    echo "Usage: docker run [options] IMAGE [SCAN_OPTIONS] <target-url>"
    echo ""
    echo "Scan Options:"
    echo "  --mode <posture|authorized>   Scan mode (default: posture)"
    echo "  --i-accept-risk               Required for authorized mode"
    echo "  --authorization-ref <file>    Path to authorization document"
    echo "  --rate-aware                  Enable respectful scanning"
    echo "  -t <seconds>                  Timeout per check"
    echo ""
    echo "Examples:"
    echo "  docker run --rm -v \$(pwd)/output:/app/output IMAGE https://example.com"
    echo "  docker run --rm -v \$(pwd)/output:/app/output IMAGE --mode posture https://example.com"
    echo ""
    exit 0
fi

# Run the SHIELD Framework scan (handles report.md generation internally)
echo "Running SHIELD Framework scan..."
cd "$FRAMEWORK_DIR"
bash scripts/run_all.sh -o "$OUTPUT_DIR" "$@"

# Check if scan succeeded
if [[ ! -d "$OUTPUT_DIR/step1" ]]; then
    echo "ERROR: Scan did not produce expected output structure"
    exit 1
fi

echo ""
echo "Post-processing outputs..."

# Consolidate JSON results into single report.json
echo "Consolidating JSON results..."
CONSOLIDATED_JSON="$OUTPUT_DIR/report.json"

# Calculate severity counts
CRIT_COUNT=$(find "$OUTPUT_DIR" -name '*.json' -exec jq -r '[.checks[]? | select(.severity == "CRITICAL" and (.status == "FAIL" or .status == "WARN"))] | length' {} + 2>/dev/null | awk '{s+=$1} END {print s+0}')
HIGH_COUNT=$(find "$OUTPUT_DIR" -name '*.json' -exec jq -r '[.checks[]? | select(.severity == "HIGH" and (.status == "FAIL" or .status == "WARN"))] | length' {} + 2>/dev/null | awk '{s+=$1} END {print s+0}')
MED_COUNT=$(find "$OUTPUT_DIR" -name '*.json' -exec jq -r '[.checks[]? | select(.severity == "MEDIUM" and (.status == "FAIL" or .status == "WARN"))] | length' {} + 2>/dev/null | awk '{s+=$1} END {print s+0}')

# Compute grade (same logic as generate_report.sh)
GRADE="A"
if [[ $CRIT_COUNT -ge 1 ]]; then GRADE="F"
elif [[ $HIGH_COUNT -ge 5 ]]; then GRADE="D"
elif [[ $HIGH_COUNT -ge 3 ]]; then GRADE="D+"
elif [[ $HIGH_COUNT -ge 1 ]]; then GRADE="C"
elif [[ $MED_COUNT -ge 3 ]]; then GRADE="C+"
elif [[ $MED_COUNT -ge 1 ]]; then GRADE="B+"
fi

# Extract target and mode from scope.json
TARGET_URL=""
SCAN_MODE="posture"
if [[ -f "$OUTPUT_DIR/step1/scope.json" ]]; then
    TARGET_URL=$(jq -r '.target // ""' "$OUTPUT_DIR/step1/scope.json" 2>/dev/null)
    SCAN_MODE=$(jq -r '.metadata.mode // "posture"' "$OUTPUT_DIR/step1/scope.json" 2>/dev/null)
fi

# Create consolidated JSON with all findings
{
    echo "{"
    echo "  \"meta\": {"
    echo "    \"timestamp\": \"$(date -u +"%Y-%m-%dT%H:%M:%SZ")\","
    echo "    \"target\": \"$TARGET_URL\","
    echo "    \"mode\": \"$SCAN_MODE\","
    echo "    \"grade\": \"$GRADE\""
    echo "  },"
    echo "  \"findings\": ["
    
    # Collect all checks from all JSON files
    FIRST=true
    for json_file in "$OUTPUT_DIR"/step*/*.json; do
        if [[ -f "$json_file" ]]; then
            while IFS= read -r check; do
                if [[ "$FIRST" == "true" ]]; then
                    FIRST=false
                else
                    echo ","
                fi
                echo "    $check"
            done < <(jq -c '.checks[]?' "$json_file" 2>/dev/null || true)
        fi
    done
    
    echo ""
    echo "  ]"
    echo "}"
} > "$CONSOLIDATED_JSON"

echo "✓ Created $CONSOLIDATED_JSON"
echo ""
echo "✅ Scan complete! Outputs:"
echo "   - $CONSOLIDATED_JSON (consolidated findings)"
echo "   - $OUTPUT_DIR/report.md (full markdown report)"
echo "   - HTML report will be generated by Scanner pipeline"
echo ""
echo "Grade: $GRADE | Critical: $CRIT_COUNT | High: $HIGH_COUNT | Medium: $MED_COUNT"
